FROM nginx:1.23.2-alpine

ENV TZ Asia/Tokyo
EXPOSE 80

WORKDIR /var/www/html

COPY ./api /var/www/html
COPY ./docker/nginx/prod/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/prod/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
